export const backgrounds = {
  title: "url('/images/title.png')",
  ixonia: "url('/images/ixonia.png')",
  tavern: "url('/images/tavern.png')",
  barkeep: "url('/images/barkeep.png')",
  patron: "url('/images/roger.png')",
  quests: "url('/images/quests.png')",
  halflingQuest: "url('/images/aurochsmaw.png')",
  shoppe: "url('/images/shoppe.png')",
  inn: "url('/images/inn.png')",
  innRoom: "url('/images/inn-room.png')",
  farm: "url('/images/farm.png')",
  abyssal: "url('/images/abyssal.png')",
  barn: "url('/images/barn.png')",
  barkeep2: "url('/images/barkeep.png')",
  croakersQuest: "url('/images/marsh.png')",
  elf: "url('/images/elf.png')",
  croakersReward: "url('/images/roger.png')",
  beholder: "url('/images/beholder.png')",
  ivy: "url('/images/elf.png')",
  beholder2: "url('/images/beholder.png')",
  dead: "url('/images/dead.png')",
  win: "url('/images/win.png')"
}